##########################################
#      SoloServerCore Configuration      #
#              Version 2.0               #
##########################################
# このコンフィグファイルはSoloServerCore v1.x との互換性はありません。
# SoloServerCore v1.x から大幅に仕様変更が行われているため、
# 一度データの初期化を行うことをオススメします。

##########################################
#            General Settings            #
##########################################

# メッセージの出力に使用する言語を指定します。
language: ja_JP

# データの保存に使用するMySQLの接続情報を設定します。
jdbc-url: jdbc:mysql://localhost:3306/MyDatabase
mysql-user: SoloUser
mysql-pass: SoloPassWord
mysql-prefix: ssc2_


##########################################
#            Function Settings           #
##########################################

random-spawn:
  # プレイヤーの初期ログインのスポーン座標をランダムにしますか？
  enable: true

  # 他プレイヤーのスポーン座標と被らないようにしますか？
  avoid-duplication: true

  # ログイン済みのプレイヤーのデータがSQLにない場合、座標を再生成しますか？
  # 無効化されている場合、その場の座標をSQLに記録します。
  regenerate-if-no-data: true

  # 生成するX座標の±最大値を指定します。
  max-random-x: 10000

  # 生成するZ座標の±最大値を指定します。
  max-random-z: 10000


invisible:
  # プレイヤー同士の視認を無効化しますか？
  enable: true

  # ログインとログアウトのメッセージを無効化しますか？
  disable-join-message: true

  # Dynmapとの連携を行いますか？
  # 2018/08/26 Dynmap連携は将来のために予約された項目です。
  # 現時点ではまだ実装されていません。
  # dynmap-support: false

  # 双方のプレイヤーが可視状態の場合のみPvPが行えるようにしますか？
  # 無効化されている場合は不可視状態でもPvPを行うことができます。
  limited-pvp: true

  # 不可視を適用しないプレイヤーを指定します。
  whitelist:
    - NAFU_at


manage-chat:
  # プレイヤーチャットを管理しますか？
  enable: true

  # プレイヤーチャットを無効化しますか？
  disable-chat: true

  # 可視設定を行っているプレイヤーのみにチャットを送りますか？
  # この項目は不可視設定が有効になっている場合のみ機能します。
  # この項目を使用するときに注意しなければいけないのは、
  # このプラグインは通常の手段でチャットを送信していないため、
  # チャット監視プラグインの管理下に置かれない可能性があります。
  limited-chat: true

  customize:
    # チャットをカスタマイズしますか？
    enable: false

    # チャットのスタイルを指定します。
    # この項目は '&' から始まるカラーコードを使用できます。
    # %Player%    発信元のプレイヤーを代入します。
    # %Message%   メッセージの内容を代入します。
    # この項目はまだ実装されていません。
    chat-style: '%Player% &6>>>&f %Message%'

  # 無効化を適用しないプレイヤーを指定します。
  whitelist:
    - NAFU_at